version: '3.8'

services:

  mock-rss-backend:
        image: golang:1.21.4-alpine3.18
        expose:
          - 80
        volumes:
          - ./aux/mock-rss-backend/source:/app/source
          - ./aux/mock-rss-backend/config.dev/www:/app/config/www
          - ./aux/mock-rss-backend/volume.dev/cache:/root/.cache
        healthcheck:
          test: wget --no-verbose --tries=1 --spider http://localhost:80/healthcheck.txt || exit 1
          interval: 10s
          timeout: 10s
          retries: 5
        working_dir: /app/source
        command: go run main.go /app/config/www


  news-db:
    image: postgres:16.2-alpine3.19
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sf
    volumes:
      - ./app/news-db/source:/docker-entrypoint-initdb.d:ro
      - ./app/news-db/volume.dev/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "sf"]
      interval: 10s
      timeout: 10s
      retries: 5


  news-backend:
    image: golang:1.21.4-alpine3.18
    environment:
      - GOPATH=/app/volume/go
    volumes:
      - ./app/news-backend/source:/app/source
      - ./app/news-backend/config.dev:/app/config:ro
      - ./app/news-backend/volume.dev/gohome:/app/volume/go
      - ./app/news-backend/volume.dev/cache:/root/.cache
    expose:
      - 80
    depends_on:
          news-db:
            condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/ping-echo || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    working_dir: /app/source
    command: go run cmd/main.go /app/config/config.json postgres://user:password@news-db:5432/sf


  comments-db:
    image: postgres:16.2-alpine3.19
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sf
    volumes:
      - ./app/comments-db/source:/docker-entrypoint-initdb.d:ro
      - ./app/comments-db/volume.dev/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "sf"]
      interval: 10s
      timeout: 10s
      retries: 5


  comments-backend:
    image: golang:1.21.4-alpine3.18
    environment:
      - GOPATH=/app/volume/go
    volumes:
      - ./app/comments-backend/source:/app/source
      - ./app/comments-backend/volume.dev/gohome:/app/volume/go
      - ./app/comments-backend/volume.dev/cache:/root/.cache
    expose:
      - 80
    depends_on:
          comments-db:
            condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/ping-echo || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    working_dir: /app/source
    command: go run cmd/main.go postgres://user:password@comments-db:5432/sf


  check-backend:
    image: golang:1.21.4-alpine3.18
    environment:
      - GOPATH=/app/volume/go
    volumes:
      - ./app/check-backend/source:/app/source
      - ./app/check-backend/volume.dev/gohome:/app/volume/go
      - ./app/check-backend/volume.dev/cache:/root/.cache
    expose:
      - 80
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/ping-echo || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    working_dir: /app/source
    command: go run cmd/main.go 


  gateway-backend:
    image: golang:1.21.4-alpine3.18
    environment:
      - GOPATH=/app/volume/go
    volumes:
      - ./app/gateway-backend/source:/app/source
      - ./app/gateway-backend/volume.dev/gohome:/app/volume/go
      - ./app/gateway-backend/volume.dev/cache:/root/.cache
    ports:
      - 8080:80
    depends_on:
          news-backend:
            condition: service_healthy
          comments-backend:
            condition: service_healthy
          check-backend:
            condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/ping-echo || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    working_dir: /app/source
    command: go run cmd/main.go
