# Этап сборки приложения
FROM golang:1.21.4-alpine3.18 as builder
WORKDIR /source
COPY . .
RUN mkdir /dest
RUN go build -o /dest/main cmd/main.go

# Этап подготовки и запуска
FROM alpine:3.18.2
LABEL project=sf-final
WORKDIR /app
COPY --from=builder /dest/main /app/main
ENTRYPOINT ["/app/main"]
